version: '3'
services:
  app:
    container_name: ${APP_CONTAINER}
    build:
      dockerfile: ./.docker/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}
      POSTGRES_TEST_DATABASE: ${POSTGRES_TEST_DATABASE}
      POSTGRES_PRO_DATABASE: ${POSTGRES_PRO_DATABASE}
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

  redis:
    container_name: ${REDIS_CONTAINER}
    image: redis:7.0
    env_file: .env
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  db:
    container_name: ${DB_CONTAINER}
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_temp_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}

volumes:
  db_temp_volume: